//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memorama.PartidaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/MemoramaService.Model")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Memorama.PartidaService.Jugador[] JugadoresActivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Memorama.PartidaService.Jugador[] JugadoresActivos {
            get {
                return this.JugadoresActivosField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadoresActivosField, value) != true)) {
                    this.JugadoresActivosField = value;
                    this.RaisePropertyChanged("JugadoresActivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/MemoramaService.Model")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PartidaService.IPartidaService")]
    public interface IPartidaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/CrearPartida", ReplyAction="http://tempuri.org/IPartidaService/CrearPartidaResponse")]
        void CrearPartida(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/CrearPartida", ReplyAction="http://tempuri.org/IPartidaService/CrearPartidaResponse")]
        System.Threading.Tasks.Task CrearPartidaAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/UnirsePartida", ReplyAction="http://tempuri.org/IPartidaService/UnirsePartidaResponse")]
        void UnirsePartida();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/UnirsePartida", ReplyAction="http://tempuri.org/IPartidaService/UnirsePartidaResponse")]
        System.Threading.Tasks.Task UnirsePartidaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/getPartidasActivas", ReplyAction="http://tempuri.org/IPartidaService/getPartidasActivasResponse")]
        Memorama.PartidaService.Partida[] getPartidasActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/getPartidasActivas", ReplyAction="http://tempuri.org/IPartidaService/getPartidasActivasResponse")]
        System.Threading.Tasks.Task<Memorama.PartidaService.Partida[]> getPartidasActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/EliminarPartida", ReplyAction="http://tempuri.org/IPartidaService/EliminarPartidaResponse")]
        void EliminarPartida(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaService/EliminarPartida", ReplyAction="http://tempuri.org/IPartidaService/EliminarPartidaResponse")]
        System.Threading.Tasks.Task EliminarPartidaAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartidaServiceChannel : Memorama.PartidaService.IPartidaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartidaServiceClient : System.ServiceModel.ClientBase<Memorama.PartidaService.IPartidaService>, Memorama.PartidaService.IPartidaService {
        
        public PartidaServiceClient() {
        }
        
        public PartidaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartidaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearPartida(string username) {
            base.Channel.CrearPartida(username);
        }
        
        public System.Threading.Tasks.Task CrearPartidaAsync(string username) {
            return base.Channel.CrearPartidaAsync(username);
        }
        
        public void UnirsePartida() {
            base.Channel.UnirsePartida();
        }
        
        public System.Threading.Tasks.Task UnirsePartidaAsync() {
            return base.Channel.UnirsePartidaAsync();
        }
        
        public Memorama.PartidaService.Partida[] getPartidasActivas() {
            return base.Channel.getPartidasActivas();
        }
        
        public System.Threading.Tasks.Task<Memorama.PartidaService.Partida[]> getPartidasActivasAsync() {
            return base.Channel.getPartidasActivasAsync();
        }
        
        public void EliminarPartida(string nombre) {
            base.Channel.EliminarPartida(nombre);
        }
        
        public System.Threading.Tasks.Task EliminarPartidaAsync(string nombre) {
            return base.Channel.EliminarPartidaAsync(nombre);
        }
    }
}
